### ISSUE TITLE
validate_string fails for integer

### ISSUE THREAD

**Issue by NoodlesNZ** [jhoblitt/puppet-ganglia#28]
When running ganglia::web with the defaults it produces this error:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: 8652 is not a string.  It looks to be a Fixnum on node ganglia.example.com

It looks like in future parser it is more strict and $ganglia_port = 8652 fails validate_string().

**Comment by jhoblitt** [comment]
#32 has been merged.
