### ISSUE TITLE
tax error at 'ganglia_ip'; expected '}' at /etc/puppet/manifests/site.pp:96 on node puppet.com

### ISSUE THREAD

**Issue by mh54** [jhoblitt/puppet-ganglia#38]
I'm new to puppet. When I install the ganglia module I keep getting the following error
tax error at 'ganglia_ip'; expected '}' at /etc/puppet/manifests/site.pp:96 on node puppet.com
Here's a copy of my site.pp.
$clusters = [
  {
    name     => 'puppet',
    address  => ['node001.com'],
  },
]
 class{ 'ganglia::gmetad':
  clusters => $clusters,
  gridname => 'my grid',
}

#class ganglia::web {
class{ 'ganglia::web':
# class{ 'ganglia::web':
  $ganglia_ip = '127.0.0.1',
  $ganglia_port = 8652,

**Comment by jhoblitt** [comment]
@mh54 It appears that you have `$` signs and `=`s in your parameter declarations for `ganglia::web`, which is invalid puppet syntax.  It should be something like

```
class{ 'ganglia::web':
  ganglia_ip => '127.0.0.1',
  ganglia_port => 8652,
}
```
