### ISSUE TITLE
Module ganglia is not supported on operatingsystemmajrelease 6 (CentOS)

### ISSUE THREAD

**Issue by NoodlesNZ** [jhoblitt/puppet-ganglia#41]
I just noticed this when updating to release 1.4.0:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Module ganglia is not supported on operatingsystemmajrelease 6 on node web1.example.com

Seems really weird because I see CentOS version 6 in the metadata.json

**Comment by NoodlesNZ** [comment]
So, I played around and it seems that this line: https://github.com/jhoblitt/puppet-ganglia/blob/master/manifests/params.pp#L65, if you change that to '6' then it works. Very strange, because this was working pre puppet 3.7.4 and/or using puppet-server

**Comment by jhoblitt** [comment]
Hmmm.  I wonder if that's a change in puppet or in facter.  Facter has been slowly changing the return type of facts away from strings.

**Comment by NoodlesNZ** [comment]
Using stdlib's type() for $::operatingsystemmajrelease returns an integer, so I've not no idea. It may have something to do with puppet-server. I'm doing some more digging.

**Comment by jhoblitt** [comment]
I suspect $::operatingsystemmajrelease should properly be a string, so I'm OK with quoting the OS versions, but this sounds like a pretty major regression that should be reported.

**Comment by NoodlesNZ** [comment]
Yup, seems to be something to do with puppet-server. If I run this with puppet apply:

```
case $::operatingsystemmajrelease {
  5: {
    notify{'This is 5':}
  }
  6: {
    notify{'This is 6':}
  }
  7: {
    notify{'This is 7':}
  }
  default: {
    notify{'Did not find':}
  }
}
```

Then it works, if I run it in site.pp via puppet-server then it falls through to the default.

**Comment by NoodlesNZ** [comment]
I'll raise a bug and see what they say.

**Comment by NoodlesNZ** [comment]
Ok, after talking to some of the puppet people on irc and doing some more testing it seems it was a change to future parser in 3.7.4. Although I don't like it, it seems the only way would be to quote the release numbers in the case statement. It seems to work with/without future parser.

I'll create a PR with a fix

**Comment by NoodlesNZ** [comment]
Ok, PR #42 fixes this problem. Closing this off.
