### ISSUE TITLE
Parse error when globals_override_hostname is not set

### ISSUE THREAD

**Issue by Debilski** [jhoblitt/puppet-ganglia#46]
Not setting `globals_override_hostname` gives

    override_hostname =

in `/etc/ganglia/gmond.conf`, which fails.

**Comment by jhoblitt** [comment]
Could you provide the error message?  What version of puppet, ruby, and stdlib did you see this failure with?  Was the future parser enabled?

**Comment by Debilski** [comment]
Puppet version 3.7.5, Puppetserver 1.0.2, Future parser, Stdlib 4.5.1, Ruby 2.1.5p273

The error message is a simple failure that ganglia cannot parse the gmond.conf file.

**Comment by jhoblitt** [comment]
@Debilski This should be fixed by #51 .  I'm going to close this issue but please reopen if it you can reproduce the ERB failure.
