### ISSUE TITLE
ganglia::udp_send_channel, etc as resources?

### ISSUE THREAD

**Issue by kitchen** [jhoblitt/puppet-ganglia#5]
What are your thoughts on having ganglia::udp_send_channel and such resources?

I would love to be able to have my collector gmonds export a udp send channel that my senders use, and have them also export clusters to gmetad, etc.

I'll do the work, and I figure we can just use like /etc/ganglia/conf.d/ sort of thing to bring in the configs so there won't even need to be any changes to the core configs (or anything silly like concat or whatever)

Thoughts?

Btw, great module, thanks for providing it!

**Comment by jhoblitt** [comment]
FYI - el5 support has been dropped from this mod.

**Comment by kitchen** [comment]
I haven’t used this puppet module in 7 years, I’ll close this issue ;)
