### ISSUE TITLE
Ganglia web conf.php template outdated

### ISSUE THREAD

**Issue by NoodlesNZ** [jhoblitt/puppet-ganglia#56]
It seems that the conf.php template (https://github.com/jhoblitt/puppet-ganglia/blob/master/templates/conf.php.el6.erb) doesn't do anything. The current ganglia on EL5, EL6 and EL7 use $conf['setting_name'] instead of $setting_name.

I'll write a PR when I get a chance, but just leaving this here as a reminder to me.

**Comment by NoodlesNZ** [comment]
See PR#57

**Comment by jhoblitt** [comment]
Closing this since #57 was merged.
