### ISSUE TITLE
typo in templates/gmond.conf.el5.erb

### ISSUE THREAD

**Issue by noemif** [jhoblitt/puppet-ganglia#68]
Hey, a really quick one:

There's a typo at templates/gmond.conf.el5.erb line 62:
`<% unless @udp_recv_channel -%>`
should be
`<% if @udp_recv_channel -%>`

This causes issues on RHEL5 where gmond fails to start with:
`apr_pollset_create failed: Invalid argument`

I've traced it down to the glibc version (2.5) which has an extra check on the apr_pollset_create() function. This check causes a failure if gmond.conf does not have at least one udp_recv_channel defined. This behaviour has been fixed in glibc >2.9 (but it's not available on RHEL5...) and in gmond 3.7.2 (but it's not yet available on EPEL...).

Cheers,
Noemi

**Comment by jhoblitt** [comment]
Sorry for the slow response. Support for el5 is being dropped, so this is not longer relevant.
