### ISSUE TITLE
Implemenation of gmond_python_modules

### ISSUE THREAD

**Issue by pramodhkp** [jhoblitt/puppet-ganglia#79]
Hi, 

Would you be interested in a PR for adding `gmond_python_modules` support for this module? https://github.com/ganglia/gmond_python_modules

I'm extending this module for my purposes, and would like to submit a PR if it's useful. 

Thanks

**Comment by jhoblitt** [comment]
#77 implements this.

**Comment by frizop** [comment]
If you check out my comments on the closed PR https://github.com/jhoblitt/puppet-ganglia/pull/77 this is roughly what I think we should do if this is needed. 

Specifically we should answer this: https://github.com/jhoblitt/puppet-ganglia/pull/77#issuecomment-690612361

Which has working tests: https://github.com/jhoblitt/puppet-ganglia/pull/77#issuecomment-690613415

etc etc. Let me know what you think!
