### ISSUE TITLE
Renewing Puppet Forge Approved Status

### ISSUE THREAD

**Issue by lionce** [jhoblitt/puppet-ganglia#80]
Hey @jhoblitt,

Here at puppetlabs, we are currently going through all of our Approved modules on the Puppet Forge. We have some feedback for your module if you would be interested in retaining the approved status. If you are keen on keeping your approved status please ensure you respond as soon as you possibly can.

Many Thanks
The Puppet Approvals Committee.

**Comment by jhoblitt** [comment]
Please!

**Comment by lionce** [comment]
Hello @jhoblitt , 

Thank you for your prompt reply. In order for this module to remain approved, the following areas need to be updated: 
	•	Add Puppet 5+6 support
	•	README should conform to documentation standards (see [here](https://puppet.com/docs/puppet/6.2/modules_documentation.html))
	•	Module should be under active maintenance (within last 6 months)
	
For additional information on Puppet Forge Approved criteria please see [here](https://forge.puppet.com/approved/criteria). 
Thank you for your cooperation. If you have any questions or concerns, don’t hesitate to let me know. 

Cheers!

**Comment by frizop** [comment]
Howdy @lionce just wondering now that there's some new modern code in this repo what the status will be updated to be? I'll note for both @jhoblitt and myself, the README.md seems a bit dated now (but most info is still accurate) and we should work on updating it. I'll also note to @jhoblitt we should look into doing a release soon, ie: the whole reason I did the work on this module :100:

**Comment by jhoblitt** [comment]
I'm planning to cut a new major release that drops puppet < 5 and el5 soonish.

**Comment by jhoblitt** [comment]
I'm currently experiencing rake target rage trying to get travis deployment to the forge up and running...

**Comment by frizop** [comment]
w00t, looks like you figured it out? I'm just now getting back to this, looks like testing is all valid locally and I see a forge release :tada:

**Comment by jhoblitt** [comment]
Yes, finally, the pdk generated `.travis.yml` isn't in a working state out of the box and the template isn't very flexible but it seems to be finally working. https://forge.puppet.com/jhoblitt/ganglia/3.0.3/readme is the version that finally made it to the forge.
