### ISSUE TITLE
Wrong package name for debian

### ISSUE THREAD

**Issue by peetbork** [jhoblitt/puppet-ganglia#96]
https://github.com/jhoblitt/puppet-ganglia/blob/9a9aaa5b2a1ab86ed6a58a476ebc47b12535cf3b/manifests/params.pp#L83
should be:
```suggestion
    $gmetad_package_name   = 'gmetad' 
```

**Comment by jhoblitt** [comment]
This should be resolved by #104

**Comment by jhoblitt** [comment]
Fix released as part of https://forge.puppet.com/modules/jhoblitt/ganglia/4.0.0/readme
