### ISSUE TITLE
restriction of maximum clusters is only 1 ?

### ISSUE THREAD

**Issue by eylenth** [jhoblitt/puppet-ganglia#97]
why is the maximum clusters in the ganglia_validate_clusters function only be 1 ?

https://github.com/jhoblitt/puppet-ganglia/blob/9a9aaa5b2a1ab86ed6a58a476ebc47b12535cf3b/lib/puppet/parser/functions/ganglia_validate_clusters.rb#L55-L57

on our environment we have like 9 clusters configured in the /etc/ganglia/gmetad.conf configuration file.
We used an older version of the ganglia puppet module, when the ganglia_validate_clusters maximum function didn't take place.

**Comment by Debilski** [comment]
It’s also not clear why it is declared as a `Tuple[Hash]`. If I change it to `Array[Hash]`, it seems to be ok with multiple clusters.

https://github.com/jhoblitt/puppet-ganglia/blob/ffe3de09527213aff54b42561597d9dc570877ab/manifests/gmetad.pp#L19-L21

**Comment by jhoblitt** [comment]
@eylenth  `#ganglia_validate_clusters` should have an arity of 1 as it only works on a single array.
@Debilski Looks like that came in as part of a cleanup PR.  I would be happy to merge a fix.

**Comment by eylenth** [comment]
@Debilski it is working now with your PR.

**Comment by jhoblitt** [comment]
Fix released as part of https://forge.puppet.com/modules/jhoblitt/ganglia/4.0.0/readme
